"use strict";
// SE port: CS:GO's panorama scripts call a set of global objects (MyPersonaAPI, PartyListAPI,
// CompetitiveMatchAPI, TournamentsAPI, GameInterfaceAPI, ...) that CS:GO's cstrike15 game DLL
// registers into the script engine.  This port has no cstrike15 client, so every CS:GO script
// aborted on its first reference - mainmenu.js died on line 8 - and the menu never faded in.
// This file installs inert, self-returning stand-ins for every global the CS:GO scripts touch,
// plus tolerant versions of the unhandled-event registration calls, so the scripts run to the end.
// Generated by build/_mkshim.ps1 from the shipped scripts; the name list is machine generated.
(function () {
	var g = Function("return this")();

	function makeStub(name) {
		var fn = function () { return makeStub(name + "()"); };
		return new Proxy(fn, {
			get: function (target, prop) {
				if (typeof prop === "symbol") { return undefined; }
				// Behave like an empty collection: panorama converts .length results straight into numbers, and a
				// stub object there made V8ParamToPanoramaType throw (and the throw took the game down).
				if (prop === "length" || prop === "size" || prop === "count") { return 0; }
				if (prop === "toString" || prop === "valueOf") { return function () { return name; }; }
				if (prop === "then") { return undefined; } // do not look like a promise
				return makeStub(name + "." + String(prop));
			},
			apply: function () { return makeStub(name + "()"); },
			construct: function () { return makeStub(name + "()"); },
			has: function () { return true; }
		});
	}

	var names = [
		"AcknowledgeItems",
		"AdvertisingToggle",
		"Avatar",
		"BlogAPI",
		"BuyMenu",
		"CalcItemCounts",
		"CapabiityHeader",
		"CapabilityCanStatTrackSwap",
		"CapabilityCanSticker",
		"CapabilityDecodable",
		"CapabilityNameable",
		"CapabilityOperationStore",
		"CharacterAnims",
		"CharacterButtons",
		"CharacterLineUp",
		"Chat",
		"Collapse",
		"CommonUtil",
		"CompetitiveMatchAPI",
		"ConstructBaseVoteIssue",
		"ConstructBaseVoteIssueEnabled",
		"Crafting",
		"Data",
		"DateUtil",
		"DeepStatsAPI",
		"DigitPanelFactory",
		"DirectChallengeCheckBox",
		"EmbeddedStreamAPI",
		"EndOfMatch",
		"EOM_Characters",
		"EOM_Podium",
		"EquipNotification",
		"EquipSpray",
		"EventUtil",
		"FlipPanelAnimation",
		"FormatText",
		"FriendAdvertiseTile",
		"FriendsListAPI",
		"Game",
		"GameInterfaceAPI",
		"GameModeFlags",
		"GameStateAPI",
		"GameTypesAPI",
		"HudEdgePositions",
		"HudMissionPanel",
		"HudWinPanel",
		"IconUtil",
		"InpsectPurchaseBar",
		"InspectActionBar",
		"InspectAsyncActionBar",
		"InspectHeader",
		"InspectModelImage",
		"InventoryAPI",
		"InventoryInspect",
		"InventoryPanel",
		"InventorySearch",
		"ItemContextEntires",
		"ItemDef",
		"ItemInfo",
		"ItemModelPanelCharWeaponInspect",
		"ItemTile",
		"LastMatch",
		"LeaderboardsAPI",
		"LicenseUtil",
		"LimitedTest",
		"LoadingScreen",
		"Loadout",
		"LoadoutAPI",
		"LobbyAPI",
		"MainMenu",
		"MainMenuStore",
		"MainMenuTournamentPassStatus",
		"MainmenuWatchNotice",
		"MapDraft",
		"MapSpiderGraph",
		"MatchDraftAPI",
		"MatchIds",
		"MatchIdsFiltered",
		"MatchInfoAPI",
		"MatchListAPI",
		"MatchLister",
		"MatchmakingReconnect",
		"MatchStats",
		"MatchStatsAPI",
		"MedalsAPI",
		"MissionsAPI",
		"MOCK_TABLE",
		"MockAdapter",
		"MuteSpinner",
		"MyPersonaAPI",
		"NewsAPI",
		"NewsPanel",
		"NextPanel",
		"OnActivate",
		"OnActivateRadioButton",
		"OnActivateShowHideConfirm",
		"OnItemPressed",
		"OnMouseOut",
		"OnMouseOutButton",
		"OnMouseOver",
		"OnMouseOverButton",
		"OnMouseOverMapTile",
		"OnSelected",
		"OnSimpleContextMenu",
		"OpBalanceReminder",
		"OpenContextMenu",
		"OperationInspect",
		"OperationMain",
		"OperationMainMenu",
		"OperationMission",
		"OperationMissionCard",
		"OperationMissions",
		"OperationStore",
		"OperationStoreInspect",
		"OperationTiers",
		"OperationUtil",
		"OptionsMenuAPI",
		"OverwatchAPI",
		"PanelPos",
		"PanoramaUI",
		"ParamsList",
		"PartyBrowserAPI",
		"PartyListAPI",
		"PartyMenu",
		"PerfItemJsContext",
		"PerfItemJsContextSingle",
		"PickemCommon",
		"PickEmInfoBar",
		"PlaqueBg",
		"PlayerStats_Web_Weapons",
		"PlayMenu",
		"PopupAcceptMatch",
		"PopupAddFriend",
		"PopupCommendPlayer",
		"PopupConfirmPickemPicks",
		"PopupGoTeamMatchmaking",
		"PopupLeaderboards",
		"PopupLimitedTest",
		"PopupNews",
		"PopupPrimeStatus",
		"PopupRedeemSouvenir",
		"PopupTournamentControlRoom",
		"PopupTournamentPickBan",
		"PopupVanitySettings",
		"PredictionsAPI",
		"ProEventJSO",
		"PromotedSettingsUtil",
		"PurchaseComplete",
		"RadarCTLogo",
		"RadarTLogo",
		"RewardItemGroups",
		"RSSFeedPanel",
		"Scheduler",
		"Scoreboard",
		"SessionUtil",
		"SetItemsToOffer",
		"SettingsMenu",
		"SettingsMenuGameSettings",
		"SettingsMenuPromoted",
		"SettingsMenuSearch",
		"SettingsMenuShared",
		"Slot",
		"StarsShoppingCart",
		"SteamOverlayAPI",
		"StoreAPI",
		"StreamPanel",
		"StreamsAPI",
		"SurvivalWinner",
		"SurvivalZoneTimer",
		"TeamColor",
		"TeammatesAPI",
		"TeamSelectMenu",
		"TintSprayIcon",
		"TooltipLobby",
		"TournamentJournal",
		"TournamentsAPI",
		"TournamentStore",
		"UIPanorama",
		"UiToolkitAPI",
		"UpdatePrediction",
		"Versus",
		"VersusCharactersMine",
		"VoteIssues",
		"VoteTeamSwitch",
		"WorkshopAPI",
		"XmlName"
	];

	for (var i = 0; i < names.length; i++) {
		var n = names[i];
		try { if (typeof g[n] === "undefined") { g[n] = makeStub(n); } } catch (e) { }
	}

	// panorama throws when a script registers for an event that no C++ code has declared; these
	// wrappers turn that into a no-op so a missing event cannot abort a whole script.
	// NOTE: do not try to declare the missing event from here - calling $.DefineEvent for a name that
	// panorama already knows *replaces* the C++ factory (and turns panel events into plain events),
	// which destabilises handlers.  Unknown names are declared on demand in C++ instead.
	function tolerant(name) {
		if (typeof $ === "undefined") { return; }
		var orig = $[name];
		if (typeof orig !== "function") { return; }
		$[name] = function () { try { return orig.apply($, arguments); } catch (e) { return 0; } };
	}
	tolerant("RegisterForUnhandledEvent");
	tolerant("UnregisterForUnhandledEvent");
	tolerant("RegisterEventHandler");
	tolerant("UnregisterEventHandler");
})();
