"use strict";
// SE port: CS:GO's panorama scripts call a set of global objects (MyPersonaAPI, PartyListAPI,
// CompetitiveMatchAPI, TournamentsAPI, GameInterfaceAPI, ...) that CS:GO's cstrike15 game DLL
// registers into the script engine.  This port has no cstrike15 client, so every CS:GO script
// aborted on its first reference - mainmenu.js died on line 8 - and the menu never faded in.
// This file installs inert, self-returning stand-ins for every global the CS:GO scripts touch,
// plus tolerant versions of the unhandled-event registration calls, so the scripts run to the end.
// Generated by build/_mkshim.ps1 from the shipped scripts; the name list is machine generated.
(function () {
	var g = Function("return this")();

	// Every stub carries two side tables:
	//   overrides - entries installed by seDefine() below; they win over the placeholder behaviour,
	//               which is how a call can be made to answer with a real 0/false/"{}" instead of
	//               another truthy stub (see the "control flow" note further down).
	//   children  - memoised child stubs, so Api.Foo === Api.Foo (identity stability).
	function makeStub(name) {
		var overrides = Object.create(null);
		var children = Object.create(null);
		var fn = function () { return makeStub(name + "()"); };
		return new Proxy(fn, {
			get: function (target, prop) {
				if (typeof prop === "symbol") {
					// ToPrimitive: JS coerces the stub whenever it lands in a JSON.parse()/string/number
					// sink.  A stub is an object, so it is *always* truthy and it can never look like a
					// "no data" answer; at least make the coercions harmless - an empty document parses,
					// and arithmetic sees 0.
					if (prop === Symbol.toPrimitive) {
						return function (hint) { return hint === "number" ? 0 : "[]"; };
					}
					return undefined;
				}
				if (hasOwn(overrides, prop)) { return overrides[prop]; }
				// Behave like an empty collection: panorama converts .length results straight into numbers, and a
				// stub object there made V8ParamToPanoramaType throw (and the throw took the game down).
				if (prop === "length" || prop === "size" || prop === "count") { return 0; }
				// Explicit .toString()/.valueOf() calls (and anything that does not go through
				// ToPrimitive) also get the harmless empty-document / zero answer.
				if (prop === "toString") { return function () { return "[]"; }; }
				if (prop === "valueOf") { return function () { return 0; }; }
				if (prop === "then") { return undefined; } // do not look like a promise
				if (!hasOwn(children, prop)) { children[prop] = makeStub(name + "." + String(prop)); }
				return children[prop];
			},
			set: function (target, prop, value) {
				if (typeof prop === "string") { overrides[prop] = value; }
				return true;
			},
			apply: function () { return makeStub(name + "()"); },
			construct: function () { return makeStub(name + "()"); },
			has: function () { return true; }
		});
	}

	function hasOwn(obj, key) { return Object.prototype.hasOwnProperty.call(obj, key); }

	var names = [
		"AcknowledgeItems",
		"AdvertisingToggle",
		"Avatar",
		"BlogAPI",
		"BuyMenu",
		"CalcItemCounts",
		"CapabiityHeader",
		"CapabilityCanStatTrackSwap",
		"CapabilityCanSticker",
		"CapabilityDecodable",
		"CapabilityNameable",
		"CapabilityOperationStore",
		"CharacterAnims",
		"CharacterButtons",
		"CharacterLineUp",
		"Chat",
		"Collapse",
		"CommonUtil",
		"CompetitiveMatchAPI",
		"ConstructBaseVoteIssue",
		"ConstructBaseVoteIssueEnabled",
		"Crafting",
		"Data",
		"DateUtil",
		"DeepStatsAPI",
		"DigitPanelFactory",
		"DirectChallengeCheckBox",
		"EmbeddedStreamAPI",
		"EndOfMatch",
		"EOM_Characters",
		"EOM_Podium",
		"EquipNotification",
		"EquipSpray",
		"EventUtil",
		"FlipPanelAnimation",
		"FormatText",
		"FriendAdvertiseTile",
		"FriendsListAPI",
		"Game",
		"GameInterfaceAPI",
		"GameModeFlags",
		"GameStateAPI",
		"GameTypesAPI",
		"HudEdgePositions",
		"HudMissionPanel",
		"HudWinPanel",
		"IconUtil",
		"InpsectPurchaseBar",
		"InspectActionBar",
		"InspectAsyncActionBar",
		"InspectHeader",
		"InspectModelImage",
		"InventoryAPI",
		"InventoryInspect",
		"InventoryPanel",
		"InventorySearch",
		"ItemContextEntires",
		"ItemDef",
		"ItemInfo",
		"ItemModelPanelCharWeaponInspect",
		"ItemTile",
		"LastMatch",
		"LeaderboardsAPI",
		"LicenseUtil",
		"LimitedTest",
		"LoadingScreen",
		"Loadout",
		"LoadoutAPI",
		"LobbyAPI",
		"MainMenu",
		"MainMenuStore",
		"MainMenuTournamentPassStatus",
		"MainmenuWatchNotice",
		"MapDraft",
		"MapSpiderGraph",
		"MatchDraftAPI",
		"MatchIds",
		"MatchIdsFiltered",
		"MatchInfoAPI",
		"MatchListAPI",
		"MatchLister",
		"MatchmakingReconnect",
		"MatchStats",
		"MatchStatsAPI",
		"MedalsAPI",
		"MissionsAPI",
		"MOCK_TABLE",
		"MockAdapter",
		"MuteSpinner",
		"MyPersonaAPI",
		"NewsAPI",
		"NewsPanel",
		"NextPanel",
		"OnActivate",
		"OnActivateRadioButton",
		"OnActivateShowHideConfirm",
		"OnItemPressed",
		"OnMouseOut",
		"OnMouseOutButton",
		"OnMouseOver",
		"OnMouseOverButton",
		"OnMouseOverMapTile",
		"OnSelected",
		"OnSimpleContextMenu",
		"OpBalanceReminder",
		"OpenContextMenu",
		"OperationInspect",
		"OperationMain",
		"OperationMainMenu",
		"OperationMission",
		"OperationMissionCard",
		"OperationMissions",
		"OperationStore",
		"OperationStoreInspect",
		"OperationTiers",
		"OperationUtil",
		"OptionsMenuAPI",
		"OverwatchAPI",
		"PanelPos",
		"PanoramaUI",
		"ParamsList",
		"PartyBrowserAPI",
		"PartyListAPI",
		"PartyMenu",
		"PerfItemJsContext",
		"PerfItemJsContextSingle",
		"PickemCommon",
		"PickEmInfoBar",
		"PlaqueBg",
		"PlayerStats_Web_Weapons",
		"PlayMenu",
		"PopupAcceptMatch",
		"PopupAddFriend",
		"PopupCommendPlayer",
		"PopupConfirmPickemPicks",
		"PopupGoTeamMatchmaking",
		"PopupLeaderboards",
		"PopupLimitedTest",
		"PopupNews",
		"PopupPrimeStatus",
		"PopupRedeemSouvenir",
		"PopupTournamentControlRoom",
		"PopupTournamentPickBan",
		"PopupVanitySettings",
		"PredictionsAPI",
		"ProEventJSO",
		"PromotedSettingsUtil",
		"PurchaseComplete",
		"RadarCTLogo",
		"RadarTLogo",
		"RewardItemGroups",
		"RSSFeedPanel",
		"Scheduler",
		"Scoreboard",
		"SessionUtil",
		"SetItemsToOffer",
		"SettingsMenu",
		"SettingsMenuGameSettings",
		"SettingsMenuPromoted",
		"SettingsMenuSearch",
		"SettingsMenuShared",
		"Slot",
		"StarsShoppingCart",
		"SteamOverlayAPI",
		"StoreAPI",
		"StreamPanel",
		"StreamsAPI",
		"SurvivalWinner",
		"SurvivalZoneTimer",
		"TeamColor",
		"TeammatesAPI",
		"TeamSelectMenu",
		"TintSprayIcon",
		"TooltipLobby",
		"TournamentJournal",
		"TournamentsAPI",
		"TournamentStore",
		"UIPanorama",
		"UiToolkitAPI",
		"UpdatePrediction",
		"Versus",
		"VersusCharactersMine",
		"VoteIssues",
		"VoteTeamSwitch",
		"WorkshopAPI",
		"XmlName"
	];

	for (var i = 0; i < names.length; i++) {
		var n = names[i];
		try { if (typeof g[n] === "undefined") { g[n] = makeStub(n); } } catch (e) { }
	}

	// panorama throws when a script registers for an event that no C++ code has declared; these
	// wrappers turn that into a no-op so a missing event cannot abort a whole script.
	// NOTE: do not try to declare the missing event from here - calling $.DefineEvent for a name that
	// panorama already knows *replaces* the C++ factory (and turns panel events into plain events),
	// which destabilises handlers.  Unknown names are declared on demand in C++ instead.
	function tolerant(name) {
		if (typeof $ === "undefined") { return; }
		var orig = $[name];
		if (typeof orig !== "function") { return; }
		$[name] = function () { try { return orig.apply($, arguments); } catch (e) { return 0; } };
	}
	tolerant("RegisterForUnhandledEvent");
	tolerant("UnregisterForUnhandledEvent");
	tolerant("RegisterEventHandler");
	tolerant("UnregisterEventHandler");

	// Install an override on a dotted API path ("MatchStatsAPI.GetUiExperienceType"), creating the
	// intermediate stubs on the way.  The value lands in the stub's override table (see makeStub).
	function seDefine(path, impl) {
		try {
			var parts = path.split(".");
			if (typeof g[parts[0]] === "undefined") { g[parts[0]] = makeStub(parts[0]); }
			var cur = g[parts[0]];
			for (var i = 1; i < parts.length - 1; i++) { cur = cur[parts[i]]; }
			cur[parts[parts.length - 1]] = impl;
		} catch (e) { }
	}

	// ------------------------------------------------------------------------------------------
	// Typed answers for the calls whose *result* decides control flow.
	//
	// A stub object is always truthy, so "if ( Api.GetSomething() ) return;" silently takes the
	// early-out branch and the button that ran that snippet appears dead, while
	// "if ( Api.GetX() !== false ) { ...popup...; return false; }" takes the error branch.  These
	// are the gates the CS:GO main menu walks through; each answer below is the truth for this port
	// (no GC connection, no license, no item schema), not a placeholder.
	// ------------------------------------------------------------------------------------------

	// mainmenu.js::_OpenPlayMenu -> "if ( MatchStatsAPI.GetUiExperienceType() ) return;" - 0 means
	// the normal main menu experience; anything truthy makes the Play button do nothing.
	seDefine("MatchStatsAPI.GetUiExperienceType", function () { return 0; });

	// mainmenu.js::_BCheckTabCanBeOpenedRightNow -> "restrictions = LicenseUtil.GetCurrentLicenseRestrictions();
	// if ( restrictions !== false ) { LicenseUtil.ShowLicenseRestrictions(...); return false; }".
	// false = "no restrictions", which is what this port has; a stub object here blocks the tab.
	// NOTE: LicenseUtil is a *script* global (common/licenseutil.js) and replaces this stub as soon as
	// that file runs, so the answer below only covers the window before it loads - the real switch on
	// MyPersonaAPI.GetLicenseType() is what normally decides, hence the "purchased" answer two lines on.
	seDefine("LicenseUtil.GetCurrentLicenseRestrictions", function () { return false; });

	// licenseutil.js::_GetCurrentLicenseRestrictions() switches on GetLicenseType():
	// "purchased" is the only case that answers false ("no restrictions"); every other value - and the
	// stub - falls through to a license popup, which would make the Store/Inventory/Watch tabs refuse
	// to open.  A port that owns no license data is the "full" case as far as the UI is concerned.
	seDefine("MyPersonaAPI.GetLicenseType", function () { return "purchased"; });

	// APIs documented to return a JSON document.  The generic stub already stringifies to "[]" (which
	// parses), but an empty document of the right shape keeps the callers on their empty-data path
	// instead of on "unexpected token" exceptions.
	seDefine("InventoryAPI.BuildItemSchemaDefJSON", function () { return "{}"; });
	seDefine("InventoryAPI.GetEconItemDefinition", function () { return "{}"; });
	seDefine("InventoryAPI.GetInventoryStructureJSON", function () { return "{}"; });
	seDefine("LoadoutAPI.GetLoadoutSlotNames", function () { return "[]"; });

	// APIs whose result is passed straight into a C++ binding that insists on a bool: the placeholder
	// object would be coerced by V8 to "" and the binding throws
	// ("V8ParamToPanoramaType expected bool type to convert, but got something else ([])"), which
	// aborts the whole script.  Observed in mainmenu_inventory.js:727
	// (elInvLoadoutBtn.enabled = LoadoutAPI.IsLoadoutAllowed()).
	// "false" is the conservative answer: the loadout button is disabled, nothing else changes.
	seDefine("LoadoutAPI.IsLoadoutAllowed", function () { return false; });

	// Same failure one level deeper: mainmenu.js::_UpdateUnlockCompAlert() builds
	//
	//     var bHide = GameInterfaceAPI.GetSettingString( ... ) === '1' ||
	//                 MyPersonaAPI.HasPrestige() ||
	//                 MyPersonaAPI.GetCurrentLevel() !== 2;
	//     alert.SetHasClass( 'hidden', bHide );
	//
	// With HasPrestige() a truthy placeholder the "||" returns that object (not a bool) and
	// SetHasClass() throws - so both of these have to answer their real type: false and 2 make the
	// expression a plain "false" and the alert stays visible (which is the pre-unlock state CS:GO
	// shows on a fresh account).
	seDefine("MyPersonaAPI.HasPrestige", function () { return false; });
	seDefine("MyPersonaAPI.GetCurrentLevel", function () { return 2; });

	// The persona/competitive answers that decide whether CS:GO throws a *modal window at the player*
	// whose buttons include "Quit".  Every one of them sits behind a truthiness test in mainmenu.js,
	// so the generic stub object turns "this port has no data" into "there is a problem", and the
	// windows that come out of it end the game when they are clicked:
	//
	//   _GcLogonNotificationReceived (mainmenu.js:189) - a non-empty GetClientLogonFatalError() falls
	//       through to ShowGenericPopupOneOptionBgStyle( "#SFUI_LoginPerfectWorld_Title_Error", ...,
	//       "#GameUI_Quit", function() { GameInterfaceAPI.ConsoleCommand( "quit" ); }, "dim" ): a
	//       window titled like an error whose *only* button quits the game.
	//   _GameMustExitNowForAntiAddiction (mainmenu.js:245) - the same shape with
	//       "#UI_AntiAddiction_ExitGameNowMessage" + "#GameUI_Quit" when
	//       GetTimePlayedTrackingState() > 0.
	//   _GetPopupNotification (mainmenu.js:1396) - shows "#SFUI_MainMenu_ConfirmBan" when
	//       GetCooldownSecondsRemaining() < 0, or when GetMyNotifications() is a non-empty string
	//       (it then calls .split( ',' ) on the result, so returning a string is required).
	//
	// This port owns no GC logon, no anti-addiction schedule and no competitive cooldown, so the empty
	// answers are the truth here.  "" rather than undefined: the callers treat the result as a string.
	seDefine("MyPersonaAPI.GetClientLogonFatalError", function () { return ""; });
	seDefine("MyPersonaAPI.GetTimePlayedTrackingState", function () { return 0; });
	seDefine("MyPersonaAPI.GetMyNotifications", function () { return ""; });
	seDefine("CompetitiveMatchAPI.GetCooldownSecondsRemaining", function () { return 0; });
	seDefine("CompetitiveMatchAPI.GetCooldownReason", function () { return ""; });
	seDefine("CompetitiveMatchAPI.GetCooldownType", function () { return ""; });

	// NOTE: deliberately *not* answered here (they stay truthy placeholders, which is the branch the
	// CS:GO menu wants when it is not connected to Steam):
	//   MyPersonaAPI.IsInventoryValid() / IsConnectedToGC()  - "false" makes
	//       _BCheckTabCanBeOpenedRightNow() refuse the Inventory/Stats tabs (it wants to pop up a
	//       Steam-connection error), so the buttons would look dead.
	//   InventoryAPI.GetCacheTypeElementFieldByIndex()       - "undefined" makes
	//       _CanOpenStatsPanel() take its "open the subscription upsell popup instead" path.

	// SE port: the CS:GO main menu background movie is named by a game setting
	// (mainmenu.js::_SetBackgroundMovie -> GameInterfaceAPI.GetSettingString('ui_mainmenu_bkgnd_movie')).
	// Only the cstrike15 client can supply it, so answer with a file that this port ships.  The name
	// is turned into "file://{resources}/videos/<name>.webm" by mainmenu.js.
	//
	// Every other setting answers "" (an unset string), NOT undefined: callers treat the result as a
	// string ("...GetSettingString( 'cl_promoted_settings_acknowledged' ).split( ':' )" in
	// common/promoted_settings.js throws on undefined and takes the whole main menu bootstrap with it).
	// SE port: GameInterfaceAPI is a *real* C++ object now - CS:GO's uicomponent_gameinterface is
	// ported (panorama/seport/gameclient/cstrike15/uicomponents/uicomponent_gameinterface.cpp) and
	// its GetSettingString/SetSettingString read and write the archived ConVars through g_pCVar, which
	// is what makes ui_mainmenu_bkgnd_movie (and with it the background-movie choice) a real setting.
	//
	// The name list above only installs a placeholder when the global is *undefined*, so the real
	// object is left alone.  seDefine() would overwrite its method, so only use it as the fallback for
	// a build without the component - and keep the "unknown setting answers '' (not undefined)"
	// contract either way: several CS:GO scripts call .split() on the result
	// (common/promoted_settings.js) and undefined would take the whole main menu bootstrap down.
	if (typeof g.GameInterfaceAPI === "undefined" ||
		typeof g.GameInterfaceAPI.GetSettingString !== "function") {
		seDefine("GameInterfaceAPI.GetSettingString", function (key) {
			if (key === "ui_mainmenu_bkgnd_movie") { return "anubis720"; }
			return "";
		});
	}
})();
