//========= Copyright Valve Corporation, All rights reserved. ============//
//
// Purpose: SE port - see se_uicomponents.h next to this file.
//
//=============================================================================//

#include "stdafx_client.h"

// Resolved through the ../panorama/seport/gameclient/cstrike15/uicomponents include dir, which is
// where the ported copy lives (CS:GO spelling, bare name).
#include "uicomponent_uitoolkit.h"

#include "se_uicomponents.h"

// memdbgon must be the last include file in a .cpp file!!!
#include <tier0/memdbgon.h>

void SE_PortInstallUiComponentBindings()
{
	static bool s_bInstalled = false;
	if ( s_bInstalled )
		return;

	if ( !panorama::UIEngine() )
	{
		Warning( "SE port: cannot install the UiToolkitAPI bindings yet - no panorama UIEngine\n" );
		return;
	}

	s_bInstalled = true;

	// CUiComponent_UiToolkit::InstallPanoramaBindings() is generated by
	// UI_COMPONENT_API_DEF_COMMON_DOC( CUiComponent_UiToolkit, UiToolkit, "..." ) ->
	// PANORAMA_COMPONENT_API_INSTALL( ..., "UiToolkitAPI", ... ), which opens the JS scope and exposes
	// the global object described by uicomponent_uitoolkit.functions.inc.
	//
	// The override is protected (UI_COMPONENT_DECLARE_GLOBAL_INSTANCE_ONLY) while
	// IUiComponentGlobalInstanceBase::InstallPanoramaBindings() is public, so call it through the base
	// pointer - exactly what CS:GO's gameui_interface.cpp does with its m_arrUiComponents list.
	IUiComponentGlobalInstanceBase *pUiToolkit = CUiComponent_UiToolkit::GetInstance();
	pUiToolkit->InstallPanoramaBindings();

	Msg( "SE port: installed the UiToolkitAPI JS bindings (CUiComponent_UiToolkit)\n" );
}
